### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by ghost**
Replace rabbitmq-management-api with a packagist source

Basically this is just a direct copy of the work @andrewmy did! This change is done for all the same reasons the comment here explains, "_A year has passed since https://github.com/richardfullmer/php-rabbitmq-management-api/pull/11 — time to move on and stop using the fork as a custom repo.﻿

This will make all the builds quicker, race-condition free, and avoid the weirdness of using a source repo in a widely used package._"

https://github.com/php-enqueue/enqueue-dev/pull/1238

### CODE REVIEW

**Comment by andrewmy** [comment]
@oreillysean good catch, when doing #1238 I forgot to update the sub-package itself. Please PR this to enqueue-dev repo, this one is a read-only split.

**Comment by ghost** [comment]
@andrewmy thanks I see now the big READ ONLY message on this repo, I'll redo this in the correct place

**Comment by andrewmy** [comment]
@oreillysean perhaps there are more places to update, would be nice to check :)

**Comment by ghost** [comment]
Will do thanks :)

**Pull request closed without merging**
